[package]
name = "azul"
version = "0.1.0"
authors = ["Felix Schütt <felix.schuett@maps4print.com>"]

[dependencies]
webrender = { git = "https://github.com/servo/webrender", rev = "3e3ee3b415f339601366dc4a9a3e54761f992a7d" }
cassowary = "0.3.0"
simplecss = "0.1.0"
twox-hash = "1.1.0"
glium = "0.20.0"
gleam = "0.4.20"
euclid = "0.16"